services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    extra_hosts: 
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"