receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      origin: otel-collector
  zipkin:
      endpoint: "http://zipkin:9411/api/v2/spans"
      format: proto
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
  # otlp:
  #   endpoint: otelcol:4317

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      # exporters: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin,otlp/jaeger]
