receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  # debug:
  #   verbosity: detailed
  #   sampling_thereafter: 2
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      origin: otel-collector
  zipkin:
      endpoint: "http://zipkin:9411/api/v2/spans"
      format: proto
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      # exporters: [prometheus, debug]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [zipkin, otlp/jaeger, otlp, debug]
      exporters: [zipkin, otlp/jaeger, otlp]
